# Generated by Django 3.2 on 2023-03-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230328_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'user'), (3, 'moderator')], default=2),
            preserve_default=False,
        ),
    ]
