# Generated by Django 3.2 on 2023-03-30 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
