# Generated by Django 3.2 on 2023-03-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(
                choices=[(1, 'Admin'), (2, 'User'), (3, 'Moderator')],
                default=2,
            ),
        ),
    ]
