# Generated by Django 3.2 on 2023-03-31 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0016_auto_20230330_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code='invalid_username',
                        message='Username must be Alphanumeric',
                        regex='^[a-zA-Z0-9]*$',
                    )
                ],
            ),
        ),
    ]
