# Generated by Django 3.2 on 2023-04-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user'), ('moderator', 'moderator')], default='user', max_length=50, null=True),
        ),
    ]
