# Generated by Django 3.2 on 2023-04-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0021_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
