# Generated by Django 3.2 on 2023-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0007_auto_20230406_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
